# Generated by Django 2.2.9 on 2020-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200103_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_year',
            field=models.CharField(max_length=4),
        ),
    ]
