# Generated by Django 2.2.9 on 2020-01-09 17:30

from django.db import migrations

def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id','telephone').iterator():
        student.telephone = ''.join(x for x in student.telephone if x.isdigit())
        student.save(update_fields=['telephone'])

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200106_1503'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
