# Generated by Django 2.2.9 on 2020-01-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200109_1730'),
    ]

    operations = [
    ]
