# Generated by Django 2.2.9 on 2020-01-21 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200106_2100'),
        ('students', '0008_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='senior_phone',
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.Teacher'),
        ),
    ]
