# Generated by Django 2.2.9 on 2020-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200121_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='senior_last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
