# Generated by Django 2.2.9 on 2020-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200126_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'FreshMan'), (2, 'Senior'))),
        ),
    ]
