# Generated by Django 2.2.9 on 2020-01-27 20:21

from django.db import migrations, models


def forward(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all().only('id', 'telephone').iterator():
        student.telephone = ''.join(x for x in student.telephone if x.isdigit())
        student.save(update_fields=['telephone'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=2, verbose_name=((1, 'FreshMan'), (2, 'Senior'))),
        ),
        migrations.RunPython(forward)
    ]
