# Generated by Django 2.2.9 on 2020-01-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200127_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.IntegerField(max_length=30),
        ),
    ]
