# Generated by Django 2.2.9 on 2020-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200127_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.CharField(max_length=20),
        ),
    ]
